services:
  - type: web
    name: rescuetron
    env: node
    plan: free
    buildCommand: npm install --include=dev --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
